### ISSUE TITLE
License expired for Fortify - even with latest autopass image

### ISSUE THREAD

**Issue by kgoossens** [admpresales/nimbus-dockerapp#1]
When running the “AOS_Web_Security_Scan_Root” job in Jenkins I get the following error:

```
[error]: Your license for Fortify SCA expired on Jan 2, 2019
com.fortify.licensing.LicenseExpiredException: Your license for Fortify SCA expired on Jan 2, 2019
	at com.fortify.licensing.Licensing.getCapabilityConfig(Licensing.java:124) ~[fortify-common-18.20.0.1071.jar:?]
	at com.fortify.licensing.Licensing.requireCapability(Licensing.java:63) ~[fortify-common-18.20.0.1071.jar:?]
	at com.fortify.sca.cmd.SCAConfiguration.initialize(SCAConfiguration.java:281) [fortify-sca-18.20.1071.jar:?]
	at com.fortify.sca.Main$Sourceanalyzer.run(Main.java:453) [fortify-sca-18.20.1071.jar:?]
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

**Comment by kgoossens** [comment]
#2 might fix this issue
